### PR TITLE
Alicia tooltip

### PR DESCRIPTION
**Pull request by ijlyttle**
These ideas are still half-baked and not ready to be merged, but I thought I would make this PR so you could see the sort of nonsense I am up to.

### CODE REVIEW

**Comment by AliciaSchep** [comment]
Looks amazing!  I think it might be worth also having the tooltip be completely optional -- it looks like right now if you don't give a tooltip argument, it still makes a tooltip.  I think that is a reasonable default but maybe there should be an easy way to say 'no tooltip', i.e. by providing `FALSE` to the tooltip argument.  Then there would be another element to the `x` list passed to the widget that is a boolean indicator of tooltip/no, and in the js code the call to the tooltip plugin is in an `if` statement.

**Comment by AliciaSchep** [comment]
Regarding the JS... 

```r 
vegalite(plot, tooltip = list(showAllFields = NULL, 
   onAppear = htmlwidgets::JS("function(title,value){console.log('appear')}")), height = 400)
```
seems to do the right thing (in the console, can see it logging each tooltip event) but requires a minor modification to the code... removing the explicit jsonlite conversion of tooltip.  The htmlwidgets code will do its own conversion to jsonlite, and that conversion seems to recognize the object created by "JS" but the jsonlite call throws an error.

For the JS hook arguments, the vega_tooltip function could check if it is either right class ("JS_EVAL") or a string (and then call `JS` to convert it to right class)

**Comment by ijlyttle** [comment]
I totally agree that no-tootip should be the default. In my rush, I did not hook up the `vega_tooltip()` function as the default `tooltip` for the `vegalite()` function. 

If things work are working right, then the default is no tooltip. You can specify `tooltip = vega_tooltip(showAllFields = NULL)` to get the encoded variables or `(showAllFields = TRUE)` to get all the fields in the data.

If might be an idea to have some syntactic sugar:

```R
vega_tooltip_encoding <- function(...){
  vega_tooltip(showAllFields = NULL, ...)
}

vega_tooltip_all <- function(...){
  vega_tooltip(showAllFields = TRUE, ...)
}
```

What would you think of such an approach?

**Comment by ijlyttle** [comment]
I have taken out the jsonlite call so that your code works:

```R
vegalite(plot, tooltip = list(showAllFields = NULL, 
   onAppear = htmlwidgets::JS("function(title,value){console.log('appear')}")), height = 400)
```

Thanks for the example - I'll go about adding in the function-call arguments now!

**Comment by AliciaSchep** [comment]
the 'sugar' functions seem like a nice addition!  I think for many use cases you might either want the default tooltip with all the fields or only the encoded field, so being to do that really easily (without having to remember something like `showAllFields =  NULL`) seems very useful!

**Comment by ijlyttle** [comment]
Thanks! 

Thanks as well for pointing out the json inefficiencies I had introduced. This is a learning experience for me, so if you see something "clunky" please continue to point it out or PR it :)

**Comment by ijlyttle** [comment]
Just checking this in for the evening - I still have a bunch of stuff to do before it's ready, but it's getting there.

**Comment by ijlyttle** [comment]
Quick question for you, this example you made got me thinking:

```r
onAppear = htmlwidgets::JS("function(title,value){console.log('appear')}"))
```

I wonder if it would be useful for us to re-export `htmlwidgets::JS()`. What do you think? 

I will be happy to implement if you think we should.

**Comment by AliciaSchep** [comment]
I think re-exporting `JS` would be a nice feature! Alternatively, the vega_tooltip function could accept regular strings for the js arguments and call `JS` internally.  The main package I know about that accepts callbacks is DT, and there the expectation is that the user calls `JS` (and that package re-exports `JS`) so that might be a good pattern to mimic

**Comment by ijlyttle** [comment]
Sounds good - I think I might also prefer the explicit call to `JS` to help distinguish (if only for the writer) those cases where the argument could be a string or a js function.

Thanks! Will re-export forthwith.

**Comment by ijlyttle** [comment]
I seem to be chasing the "great whale" trying to get Travis to work. Taking a wee break, for the moment.

Some notes, if only for my own benefit (these notes probably belong elsewhere). In the short term:

- on Travis, we need to install a version of Python >= 3.5, then install the Altair package to *that* installation. 
- further, we need to note *where* that installation is, so that we can set `RETICULATE_PYTHON`.

Longer term:

- it will be great to have a standard procedure to follow, both for our own personal installations and for Travis. JJ seems to be gravitating towards using a single Conda installation named "r-reticulate", which is all to the good.
- Altair (v2) is not yet available on Conda.

**Comment by ijlyttle** [comment]
I got Travis to work 🎉🎉🎉

Sorry to have fouled this PR so completely with this quest that should have been made elsewhere...

I have a few things I'd like to clean up, then have you give this your "benediction" (if you think it merits it).

**Comment by ijlyttle** [comment]
I think this is finally ready for your consideration. Sorry for the mess. 

From my perspective, the tooltips seem operational and the API seems reasonable. Please let me know if you think otherwise.

I think you have seen the tooltip article added here - it goes over the functions and philosophy, at least as I understand it.

There are a few things to clean up; I have a few TODO's sprinkled here and there, but I think it may be ready to begin its trip back to the master branch. 

If/when you are OK with this PR, please merge, then I'll merge your PR.

Thanks again!

**Comment by AliciaSchep** [comment]
Looks **terrific**!  Just catching up on this thread, and glancing over the commits it looks like it was quite a saga :smile: Love the detailed vignette on the tooltip.  

I temporarily encountered an issue with the `examine` function but was able to trace it to a package version issue with listviewer (updating that package resolved the issue).  Once I merge I will add a package version requirement to the suggests field of the DESCRIPTION page for listviewer.

**Comment by ijlyttle** [comment]
Thanks for the catch on listviewer!

**Pull request merged**
